config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :albums, shallow: true do
      resources :images, shallow: true do
        member do
          get 'cover'
        end
      end
    end
  end
  resources :images, only: [:index]
  resources :sessions, only: [:new, :create, :destroy]
  resources :albums
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  root 'static_pages#home'
end

app/models/user.rb
#
class User
  include Mongoid::Document
  include ActiveModel::SecurePassword
  extend Dragonfly::Model
  field :name, type: String
  field :email, type: String
  field :password_digest, type: String
  field :created_at, type: DateTime
  field :updated, type: DateTime
  field :image_uid, type: String
  field :image_name, type: String
  field :album_uid, type: String
  field :admin, type: Boolean, default: false
  has_secure_password
  has_many :albums
  has_many :images
  accepts_nested_attributes_for :albums
  dragonfly_accessor :image

  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :email,
            format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i },
            presence: true,
            uniqueness: { case_sensitive: false }

  # query: Return a null user object
  #
  # Returns a Struct which responds to id, email, username, and authenticate
  #
  # @return [User] User duck
  #
  def self.null_user
    NullUser.new
  end

  # User duck type for null user pattern
  #
  class NullUser
    attr_reader :id, :email, :username
  end
end

app/controllers/users_controller.rb
#
class UsersController < ApplicationController
  before_action :require_login, except: [:new, :create, :index, :show]
  before_action :ensure_current_user, only: [:edit, :udpate]
  include ProfileHelper

  def new
    @user = User.new
  end

  def index
    @users = User.all.paginate(page: params[:page], per_page: '6')
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id.to_s
      flash[:success] = 'Signed Up'
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if user.update_attributes(user_params)
      flash[:success] = 'Successfully Updated'
      redirect_to user_path(user)
    else
      render 'edit'
    end
  end

  private

  def user
    @user = User.find(params[:id])
  end

  def find_user
    @user = User.find(params[:id])
    redirect_to root_path unless @user == current_user
  end

  def user_params
    params.require(:user).permit(:name, :username, :email, :password,
                                 :password_confirmation, :image, :album)
  end
end

app/views/users/_form.html.haml
.row
  .col-md-6.col-md-offset-3
  = form_for(@user) do |f|
    = render partial: 'shared/error_messages', locals: {model: @user}
    = f.label :name
    = f.text_field :name, class: 'form-control'
    = f.label :email
    = f.email_field :email, class: 'form-control'
    = f.label :password
    = f.password_field :password, class: 'form-control'
    = f.label :password_confirmation, "Confirmation"
    = f.password_field :password_confirmation, class: 'form-control'
    %br
    = f.label :image
    = f.file_field :image
    %br
    = f.submit "Submit", class: "btn btn-primary"

app/views/users/edit.html.haml
- provide(:title, 'Edit Profile')
%h1 Edit Your Profile
= "#{@user.name}"

= render 'form'

app/views/users/index.html.haml
- provide(:title, 'User Index')
= will_paginate @users
%h1 Index of Users

%table{:style => "width:500px"}/
%thead/
%tr
  %th{:style => "text-align:right;"} Name
  %th{:style => "text-align:right;"} email
- @users.each do |user|

  %tr
    %td{:style => "text-align:right;"}= link_to user.name, user
    %td{:style => "text-align:right;"}= user.email
    %td{:style => "text-align:right;"}= admin_account(user)

app/views/users/new.html.haml
- provide(:title, 'Sign up')
%h1 Sign up

= render partial: 'form'

app/views/users/show.html.haml
- provide(:title, 'User Home')
%h5 Welcome
= "#{@user.name}, #{@user.email}"
= link_to 'Admin Review', images_path if @user.admin?
%br
%br
= image_tag @user.image.thumb('200x200#').url if @user.image_stored?
%br
%p= link_to 'New Album', new_user_album_path(current_user)
%br
%br
%h5 Your Albums
- @user.albums.each do |album|
  = div_for(album) do
    = link_to album.name, album
    = image_tag album.thumb_url