config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :albums, shallow: true do
      resources :images, shallow: true do
        member do
          get 'cover'
        end
      end
    end
  end
  resources :images, only: [:index]
  resources :sessions, only: [:new, :create, :destroy]
  resources :albums
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  root 'static_pages#home'
end

app/models/album.rb
#
class Album
  include Mongoid::Document
  field :name, type: String
  field :user_id, type: String
  field :image_id, type: String
  belongs_to :user
  belongs_to :cover, class_name: "Image"
  has_many :images
  delegate :thumb_url, to: :cover, allow_nil: true

  validates :name,
            presence: true,
            uniqueness: { case_sensitive: false, scope: :user_id }

  # query: Returns whether the given image is the cover for this album
  #
  # @return [Boolean]
  # stolen
  #
  def cover?(image)
    cover == image
  end
end

app/controllers/albums_controller.rb
#
class AlbumsController < ApplicationController
  before_action :require_login, except: [:show, :index]
  before_action :ensure_current_user, except: [:show, :index]
  def show
    @album = album
  end

  def new
    @album = current_user.albums.new
  end

  def edit
    @album = album
  end

  def index
    @albums = Album.all.paginate(page: params[:page], per_page: '10')
  end

  def create
    @album = current_user.albums.new(album_params)
    if @album.save
      flash[:success] = 'Success!'
      redirect_to album_path(@album)
    else
      render 'new'
    end
  end

  def update
    if @album.update_attributes(album_params)
      flash[:success] = 'Successfully Updated'
      redirect_to user_album_path(current_user)
    else
      render 'edit'
    end
  end

  private

  def album
    @album ||= Album.find(params[:id])
  end

  def user
    return album.user unless params[:user_id].present?
    @_album ||= User.find(params[:user_id])
  end

  def album_params
    params.require(:album).permit(:name)
  end
end
# Tom's solution: user.albums.build for each Album
# keeping comment to remember question

app/helpers/albums_helper.rb
#
module AlbumsHelper
  def update_album_link(album)
    return update_album_link!(album) if permitted?(album.user)
    ''
  end

  def create_cover_link(image)
    return '' unless permitted?(image.user)
    return '' if image.album.cover?(image)
    create_cover_link!(image)
  end

  private

  def create_cover_link!(image)
    link_to 'Make Primary', cover_image_path(image)
  end

  def update_album_link!(album)
    link_to edit_album_path(album)
  end
end

app/views/albums/_album_form.html.haml
= form_for [@album.user, @album] do |f|
  = render partial: 'shared/error_messages', locals: {model: @album}
  = f.label :name
  = f.text_field :name, class: 'form-control'
  %br
  = f.submit "Submit", class: "btn btn-primary"

app/views/albums/edit.html.haml
= render 'album_form'

app/views/albums/index.html.haml
%h5 #{link_to "Create an Album", new_user_album_path(current_user)}

app/views/albums/new.html.haml
%h1 You need more albums!
=render partial: 'album_form', locals: {model: @album}

app/views/albums/show.html.haml
%h2= "#{@album.name} by #{ link_to @album.user.name, @album.user }".html_safe
%h5 #{link_to "Update Your Album", edit_album_path(@album)}

%h5 #{link_to "Add an Image", new_album_image_path(@album)}

- @album.images.each do |image|
  = div_for(image) do
    = image_tag image.thumb_url
    = link_to image.name, image
    = create_cover_link(image)